# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Forge 1.12.2

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Setup base workspace
        run: ./gradlew Forge:Base:setupDecompWorkspace
      - name: Build with Gradle
        run: ./gradlew Forge:1.12.2:build
      - name: Rename artifacts
        run: mv Forge/1.12.2/build/libs/MineCity-Forge-MC1.12.2-*.jar Forge/1.12.2/build/libs/MineCity-Forge-MC-1.12.2.jar
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: MineCityForge1.12.2
          path: Forge/1.12.2/build/libs/MineCity-Forge-MC-1.12.2.jar
